name: Haiku PR - Composite Action -  Build Test Upload

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'haiku-src/**'

jobs:
  pr-composite-action-build-and-test-haiku:

    name: Build and test haiku on PR using Composite Action

    runs-on: ubuntu-latest

    steps:

      - name: Start Build Indicator
        run: |
          curl -X POST "https://api.lifx.com/v1/lights/${{ vars.LIFX_BULB_LOCATION }}/effects/breathe" -H "Authorization: Bearer ${{ secrets.LIFX_TOKEN }}" -d 'color=blue' -d 'period=4' -d 'cycles=450' -d 'from_color=pink'
    
      - name: Build, test, and create deployment files for Haiku
        uses: devopselvis/haiku-composite-action-build-test-upload-results@main
        with:
          haiku-src-path: 'haiku-src'

      - name: Final build status indicator
        if: success()
        run: | 
          curl -X POST "https://api.lifx.com/v1/lights/${{ vars.LIFX_BULB_LOCATION }}/effects/off" -H "Authorization: Bearer ${{ secrets.LIFX_TOKEN }}" -d 'power_off=false'
          curl -X PUT "https://api.lifx.com/v1/lights/${{ vars.LIFX_BULB_LOCATION }}/state" -H "Authorization: Bearer ${{ secrets.LIFX_TOKEN }}" -d 'color=green'
        
      - name: Final build status indicator
        if: failure()
        run: | 
          curl -X POST "https://api.lifx.com/v1/lights/${{ vars.LIFX_BULB_LOCATION }}/effects/off" -H "Authorization: Bearer ${{ secrets.LIFX_TOKEN }}" -d 'power_off=false'
          curl -X PUT "https://api.lifx.com/v1/lights/${{ vars.LIFX_BULB_LOCATION }}/state" -H "Authorization: Bearer ${{ secrets.LIFX_TOKEN }}" -d 'color=red'
      
