# Name of workflow
name: MyWebApp - Publish Release - Reusable Workflow

# Workflow trigger event. We want the workflow to trigger on a pull
# request to main
on:
  release:
    types: 
      - published
      
permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
  
jobs:

  deploy-to-dev:
    name: Deploy to DEV environment
    uses: mickeygoussetorg/github-actions-presentation/.github/workflows/mywebapp-reusable-workflow-deploy-web-app.yml@mickeygousset/release-demo
    with:
      runs-on: ubuntu-latest
      artifact-to-deploy: mywebapp
      env-name: DEV
      env-url: https://github-actions-talk-dev.azurewebsites.net
      app-name: github-actions-talk-dev
      version-number: ${{github.event.release.tag_name}}
    secrets: inherit
    
  deploy-to-staging:
    name: Deploy to STAGING environment
    uses: mickeygoussetorg/github-actions-presentation/.github/workflows/mywebapp-reusable-workflow-deploy-web-app.yml@mickeygousset/release-demo
    with:
      runs-on: ubuntu-latest
      artifact-to-deploy: mywebapp
      env-name: STAGING
      env-url: https://github-actions-talk-staging.azurewebsites.net
      app-name: github-actions-talk-staging
      version-number: ${{github.event.release.tag_name}}
    secrets: inherit
    
  deploy-to-prod:
    name: Deploy to PROD environment
    needs: 
      - deploy-to-dev
      - deploy-to-staging
    uses: mickeygoussetorg/github-actions-presentation/.github/workflows/mywebapp-reusable-workflow-deploy-web-app.yml@mickeygousset/release-demo
    with:
      runs-on: ubuntu-latest
      artifact-to-deploy: mywebapp
      env-name: PROD
      env-url: https://github-actions-talk-prod.azurewebsites.net
      app-name: github-actions-talk-prod
      version-number: ${{github.event.release.tag_name}}
    secrets: inherit
      
